### PR TITLE
feat: &depupdate=0 skips helm dependencies update

### LINKED ISSUE #6: Istio setup
Following-up @xeor question about istio from #4

```
$ helm repo add istio git+https://github.com/istio/istio@install/kubernetes/helm/istio
Error: directory /tmp/helm-git.prEvHt/install/kubernetes/helm/subcharts/sidecarInjectorWebhook not found
```

This is intended as `helm-git` does a [sparse checkout](https://git-scm.com/docs/git-read-tree#_sparse_checkout) instead of a full one, and thus is not pulling other folders than `install/kubernetes/helm/istio`.

You can workaround this error by using the helm charts root as folder instead of istio:
```
$ helm repo add istio git+https://github.com/istio/istio@install/kubernetes/helm
``` 

Once there, another error blocks us from installing istio:
```
Error: no repository definition for @istio.io. Please add them via 'helm repo add'
```

This error appears as the istio chart (and `istio-remote` one) depends on `istio.io` repository for the `istio-cni` subchart, see: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/requirements.yaml#L62 https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio-remote/requirements.yaml#L16

Adding `istio-cni` repository as `istio.io` in helm does the trick! 
```
helm repo add istio.io git+https://github.com/istio/cni@deployments/kubernetes/install/helm/istio-cni
helm repo add istio git+https://github.com/istio/istio@install/kubernetes/helm
```

@xeor Can you confirm these steps solves your problem? 

Related https://github.com/istio/istio.io/issues/2787

### PR DESCRIPTION
**Pull request by akavel**
Fixes #6

```
$ HELM_GIT_DEBUG=1 helm repo add mctmp01 'git+https://github.com/istio/istio@install/kubernetes/helm?ref=1.5.4&sparse=0&depupdate=0'
Debug in plugin 'helm-git': repo: https://github.com/istio/istio ref: 1.5.4 path: install/kubernetes/helm file: index.yaml sparse: 0
Debug in plugin 'helm-git': helm_repo_uri: git+https://github.com/istio/istio@install/kubernetes/helm?ref=1.5.4&sparse=0
"mctmp01" has been added to your repositories
```

Sorry for not updating docs, don't have time :(

### CODE REVIEW

**Comment by aslafy-z** [comment]
Thanks for your contribution? Could you add a test case? Thanks!

**Comment by akavel** [comment]
@aslafy-z ohhhhh, I didn't realize there are tests here! What do you think I should test? Just the positive case for istio, or something else?

**Comment by akavel** [comment]
Added some test!

**Comment by aslafy-z** [comment]
Released as [`v0.10.0`](https://github.com/aslafy-z/helm-git/releases/tag/v0.10.0). Big thanks!

**Comment by akavel** [comment]
And thank you first of all for creating this awesome plugin! ❤️

**Pull request merged**
