### PR TITLE
fix: remove skip-refresh from helm_dependency_update

### PR DESCRIPTION
**Pull request by dunaev-opsfleet**
This PR is created in to possibly close https://github.com/aslafy-z/helm-git/issues/134
As @FalconerTC mentioned in https://github.com/aslafy-z/helm-git/issues/134#issuecomment-783749269 , after deleting `--skip-refresh` parameter from `helm_dependency_update` function issue with cached repos disappears.

### CODE REVIEW

**Comment by iAnomaly** [comment]
> For some reason, this PR does not passes the tests. It looks like an infinite loop. I have no extra time to look at this today, will check ASAP.

Any chance you'll get to this soon @aslafy-z? Much appreciated!

**Comment by metajiji** [comment]
Still problem.

**Comment by aslafy-z** [comment]
https://github.com/aslafy-z/helm-git/pull/189 takes precedence over this PR. Thank you for your work @dunaev-opsfleet

**Pull request closed without merging**
