### PR TITLE
fix: Fix fetching annotated tags

### PR DESCRIPTION
**Pull request by arkaitzj**
Discovered a bug while fetching annotated tags where we cannot do a standard fetch Tag

### CODE REVIEW

**Comment by arkaitzj** [comment]
hmm, I wonder why tests pass locally, I will check

**Comment by arkaitzj** [comment]
@aslafy-z is the github action ok?

**Comment by aslafy-z** [comment]
@arkaitzj I fixed the CI! Can you please implement some tests for it?

**Comment by maxime1907** [comment]
@arkaitzj Any update on this ?

**Comment by maxime1907** [comment]
bump

**Comment by aslafy-z** [comment]
@maxime1907 This new functionnality needs integration tests. Can you write some? I can help if needed.

**Comment by aslafy-z** [comment]
Should be fixed with #265

**Pull request closed without merging**
