### PR TITLE
Pulling value files are not helm 3 exclusive

### PR DESCRIPTION
**Pull request by jkroepke**
This feature runs inside helm 2 CI/CD?

### CODE REVIEW

**Comment by aslafy-z** [comment]
Does this work on your side? I'll add some tests with #130

**Comment by jkroepke** [comment]
Yes.

```
jkr@joe-nb ~ % helm version -c
Client: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}

jkr@joe-nb ~ % helm plugin install https://github.com/aslafy-z/helm-git --version 0.10.0
Installed plugin: helm-git

jkr@joe-nb s % helm create test
Creating test

jkr@joe-nb s % rm -fr test/templates/* test/values.yaml
jkr@joe-nb s % echo '{{ .Values | toYaml }}' > test/templates/values.yaml

jkr@joe-nb s % helm template test -f 'git+https://github.com/jkroepke/helm-secrets@tests/assets/values/noop/secrets.yaml?ref=master'
---
# Source: test/templates/values.yaml
global_secret: global_bar
key: |-
  -----BEGIN PGP MESSAGE-----

  wcFMAxYpv4YXKfBAARAAVzE7/FMD7+UWwMls23zKKLoTs+5w9GMvugn0wi5KOJ8P
  PSrRY4r27VhwQH38gWDrzo3RCmO9414xZ0JW0HaN2Pgd3ml6mYCY/5RE7apgGZQI
  3Im0fv8bhIwaP2UWPp74EXLzA3mh1dUtwxmuWOeoSq+Vm5NtbjkfUt/4MIcF5IAY
  c+U4ZOdQlzgExwu+VtOpeBrkwfglh5fFuKqM8Fg1IICi/Pp6YAlpAdGqlt1zS4Pj
  yjAS6eAvnpM0eA5hShuoO9JsAu4kVjaaBlipVpc1I2zdcT3H/1d7ASziwbKOm6jE
  PJxzaMDxn0UfMjkhTaTZ8v27lz6W7qdlHdCWGGI348QkSoDotm7OzMC7ZLfps3+9
  GrXo9Kwxkj6oy/thn92W2cRSeSD28g6kcUkHeG8L3mMv+gpTjIhM+Z8x3jJcVp2i
  yoA2dO/kO2/HTcUfnEjppKigqUlRuKfDn8ercjYiq+foqtimH192iXXyRmltYlH0
  GUSJ1FcNLAC9g0WLFPQnMFh5KxSweavpbdd6PILqEsyKvZpC5a+hzLKwGjWOveW1
  K34QZf6Ay3CPCegAyGVjxmsg1vPKD+9WAZinveCl37l3cCQW1VZzbGkHgtLQ30Qr
  DCRFZEstraLAQUf6VLAk9bPYX/fvkXmra970i/CfJjIg0SpOXbADBR4x+zRRZqrS
  4AHkWTmhH/xXWyAgmh+sGs18OOFGfeC04AjhMmvg4uKzly6+4IDlNhPif2VpJYOi
  EmU8gQoUsAHKYro0hPfzBZyJlL+TqCPgHeRPANVgm4Ww6RlVrNFpTy9H4m4s5y/h
  EzAA
  =jf7D
  -----END PGP MESSAGE-----
service:
  port: 81

```

**Comment by aslafy-z** [comment]
:rocket: PR was released in [`v0.10.1`](https://github.com/aslafy-z/helm-git/releases/tag/v0.10.1) :rocket:

**Pull request merged**
