### PR TITLE
feat: remove filename restrictions

### PR DESCRIPTION
**Pull request by jkroepke**
Fixes: #119

### CODE REVIEW

**Comment by jkroepke** [comment]
I'm using my branch in my CI. It works fine.

**Comment by aslafy-z** [comment]
Looks good! Can you add at least one test case?

**Comment by jkroepke** [comment]
> Can you add at least one test case?

Done.

Take a look at:

https://github.com/bats-core/bats-assert
https://github.com/bats-core/bats-file

It should improve the readability of the test files.

Take a look here: https://github.com/jkroepke/helm-secrets/blob/master/tests/unit/clean.bats

**Comment by jBouyoud** [comment]
@aslafy-z Does it ready to merge and release ?

**Comment by jkroepke** [comment]
@jBouyoud you could take a look why tests are failed.

**Comment by jBouyoud** [comment]
@jkroepke `--repo` flag is not supported on helm 2. 

Maybe you can move your test to `03-cli.bats`  and use something like : 
```
@test "fetch tests/fixtures/example-chart/values.yaml" {
    run helm_init "$HELM_HOME"
    url="git+https://github.com/aslafy-z/helm-git@tests/fixtures/example-chart/values.yaml?ref=master"
    $HELM_GIT_DIRNAME/helm-git "" "" "" "$url" 2>/dev/null > "$HELM_GIT_OUTPUT/values.yaml"
    [ $? = 0 ]
    run stat "$HELM_GIT_OUTPUT/values.yaml"
    [ $status = 0 ]
}

```

**Comment by jkroepke** [comment]
> flag is not supported on helm 2.

The whole feature does not exist in Helm 2.

**Comment by jBouyoud** [comment]
@jkroepke I don't understand your comment about Helm 2. 
Based on https://github.com/aslafy-z/helm-git/blob/master/helm-git-plugin.sh#L96, this plugin seems design for Helm 2 and hopefully works on Helm3. 

This commit https://github.com/jBouyoud/helm-git/commit/345cc81692d126e4d116c8309cb48da52e5eb49b add a test for this feature and remove the non compatible one. You can cherry pick it, I cannot push to your branch.

**Comment by aslafy-z** [comment]
Thanks @jkroepke @jBouyoud for your work. You're right, this plugin was designed at the time of Helm 2 and some contributors worked on it to add support for Helm 3. I want to make it Helm 3 first in the future, will see when I get time to work on it.

@jkroepke can you merge in @jBouyoud change so we can push this? Thanks!

**Comment by jkroepke** [comment]
> @jkroepke I don't understand your comment about Helm 2.

I thought, the download plugins are helm 3 exclusive feature. But this is wrong.

**Comment by jkroepke** [comment]
> @jkroepke can you merge in @jBouyoud change so we can push this forward?

**Comment by jkroepke** [comment]
Test are green, but tests are not executed.

**Comment by aslafy-z** [comment]
Released as [`v0.10.0`](https://github.com/aslafy-z/helm-git/releases/tag/v0.10.0). Big thanks!

**Pull request merged**
