### PR TITLE
fix: parser to work with forward slashes in ref param

### LINKED ISSUE #123: Bug: Plugin does not work when git ref contains a forward slash
In our company, we are using git branch names in patern `feature/123` <- _Mind the froward slash_
Due to parsing pattern in the plugin this does not work properly

`helm-git` version: 0.8.1

## Steps To Reproduce

1. Run `HELM_GIT_DEBUG=1 helm repo add elastic git+https://github.com/elastic/helm-charts@elasticsearch?ref=example/settings-and-inheritance`

2. You're going to get:
```
Debug in plugin 'helm-git': repo: https://github.com/elastic/helm-charts ref: example/settings-and-inheritance path: elasticsearch/index.yaml?ref=example file: settings-and-inheritance sparse: 1
Debug in plugin 'helm-git': helm_repo_uri: git+https://github.com/elastic/helm-charts@elasticsearch/index.yaml?ref=example?ref=example/settings-and-inheritance&sparse=1
Error in plugin 'helm-git': Target file name has to be either 'index.yaml' or a tgz release
Error: looks like "git+https://github.com/elastic/helm-charts@elasticsearch?ref=example/settings-and-inheritance" is not a valid chart repository or cannot be reached: plugin "helm-git" exited with error
```

3. Tak a look at `path` and `file` in the debug output.

## The expected behavior

1. Run `HELM_GIT_DEBUG=1 helm repo add elastic git+https://github.com/elastic/helm-charts@elasticsearch?ref=example/settings-and-inheritance`

- Output:
```
Debug in plugin 'helm-git': repo: https://github.com/elastic/helm-charts ref: example/settings-and-inheritance path: elasticsearch file: index.yaml sparse: 1
Debug in plugin 'helm-git': helm_repo_uri: git+https://github.com/elastic/helm-charts@elasticsearch?ref=example/settings-and-inheritance&sparse=1
"elastic" has been added to your repositories
```

### PR DESCRIPTION
**Pull request by DzeryCZ**
Fixes #123

### CODE REVIEW

**Review by raresociopath — APPROVED** [review]

**Comment by raresociopath** [comment]
@DzeryCZ Is it possible to merge this?

**Comment by raresociopath** [comment]
Tested and it works fine, btw.

**Comment by DzeryCZ** [comment]
Yep. If it looks good to you please merge.
Thanks.

**Comment by aslafy-z** [comment]
Thanks for your contribution! Will release ASAP

**Comment by aslafy-z** [comment]
https://github.com/aslafy-z/helm-git/releases/tag/v0.9.0 was released and includes this fix.

**Pull request merged**
